[package]
name = "limn"
version = "0.1.0"
authors = ["Chris Tolliday <ctolliday@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
text_layout = { path = "text_layout" }
limn-layout = { path = "layout" }
cassowary = { git = "https://github.com/christolliday/cassowary-rs", rev = "0329f1799dd606e999f26407f06169e0b7d408f8" }

euclid = "0.15.1"
log = "0.3"
gleam = "0.4.7"

webrender = { git = "https://github.com/servo/webrender", rev = "9e1a85e8226d7746e82902f44467293d1a9938ca" }
webrender_api = { git = "https://github.com/servo/webrender", rev = "9e1a85e8226d7746e82902f44467293d1a9938ca" }

rusttype = "0.2.1"
piston2d-graphics = "0.21"
glutin = "0.9.1"

lazy_static = "0.2.2"
linked-hash-map = "0.3.0"
stable_bst = "0.2.0"
maplit = "0.1.4"
downcast-rs = "1.0.0"
multi_mut = "0.1.3"

[dev-dependencies]
find_folder = "0.3.0"
chrono = "0.2.25"
env_logger = "0.3"

[features]
nightly = []
default = ["nightly"]
