[package]
name = "limn"
version = "0.1.0"
authors = ["Chris Tolliday <ctolliday@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
text_layout = { path = "text_layout" }
limn-layout = { path = "layout" }
cassowary = { git = "https://github.com/christolliday/cassowary-rs", rev = "8c6927c8c3e93a5cdf66513ad504b6d9a2c17471" }

euclid = "0.15.1"
log = "0.3"
gleam = "0.4.7"

webrender = { git = "https://github.com/servo/webrender", rev = "c3376c8049c01827872cc85a865b8e80a4532bdd" }
webrender_api = { git = "https://github.com/servo/webrender", rev = "c3376c8049c01827872cc85a865b8e80a4532bdd" }

stb_truetype = "0.2.1"
app_units = "0.5"
rusttype = "0.2.1"
glutin = "0.9.1"
image = "0.15"

lazy_static = "0.2.2"
linked-hash-map = "0.3.0"
stable_bst = "0.2.0"
maplit = "0.1.4"
downcast-rs = "1.0.0"
multi_mut = "0.1.3"

[dev-dependencies]
find_folder = "0.3.0"
chrono = "0.2.25"
env_logger = "0.3"
lipsum = "0.3"
rand = "0.3"

[features]
nightly = []
default = ["nightly"]
