[package]
name = "limn"
version = "0.1.0"
authors = ["Chris Tolliday <ctolliday@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
backend = { path = "backend" }
text_layout = { path = "text_layout" }
cassowary = { git = "https://github.com/christolliday/cassowary-rs", rev = "bcfaf0e0f767a7c75aa8987e64783a8f57bde6ce" }

petgraph = "0.4.3"

rusttype = "0.2.1"
piston2d-graphics = "0.21"
gfx_device_gl = "0.13.0"
piston2d-gfx_graphics = "0.38.0"
glutin = "0.7.0"

lazy_static = "0.2.2"
linked-hash-map = "0.3.0"
stable_bst = "0.2.0"
maplit = "0.1.4"
downcast-rs = "1.0.0"

[dev-dependencies]
find_folder = "0.3.0"
chrono = "0.2.25"
