[package]
name = "limn-layout"
version = "0.1.0"
authors = ["Chris Tolliday <ctolliday@gmail.com>"]

[dependencies]
cassowary = { git = "https://github.com/christolliday/cassowary-rs", rev = "1e60624fa7267a8a8e4c31362eac9305aa29ccdd" }
euclid = "0.15.1"
log = "0.3"
lazy_static = "0.2.2"

[dev-dependencies]
maplit = "0.1.4"
