[package]
name = "limn-layout"
version = "0.1.0"
authors = ["Chris Tolliday <ctolliday@gmail.com>"]

[dependencies]
cassowary = { git = "https://github.com/christolliday/cassowary-rs", rev = "8c6927c8c3e93a5cdf66513ad504b6d9a2c17471" }
euclid = "0.15.1"
log = "0.3"
lazy_static = "0.2.2"

[dev-dependencies]
maplit = "0.1.4"
